### ISSUE TITLE
Bot dashboard

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#290]
Make a dashbord on yata website to allow admins to change their configuration

- [x] dashboard (web)
- [x] update function (bot)

**modules**
- [x] Rackets
- [x] Verify
- [x] Loot
- [x] Chain
- [x] OC
- [x] API
- [x] Revive
- [x] Misc
- [x] admin

**todo**
- [x] create custom prefix
- [x] add join date
- [x] add a secret key to each server for read only configuration
- [x] clear list of permissions needed for each module/command
